import json
import os
import pytest
from opioid_track.core import geographic_joiner
from opioid_track import config

def test_risk_tier_boundaries():
    """Test standardizing short FIPS to 5 digits."""
    pass # No longer applicable, testing boundaries instead



def test_missing_data_handling():
    """Test min_max_scale handles missing (None) and zero range gracefully."""
    assert geographic_joiner.min_max_scale(None, 0, 100) == 0.0
    assert geographic_joiner.min_max_scale(50, 0, 100) == 0.5
    assert geographic_joiner.min_max_scale(100, 100, 100) == 0.0  # max == min


def test_output_json_loads():
    """Test that output JSON generated by Geographic Joiner loads completely."""
    assert os.path.exists(config.GEO_PROFILES_OUTPUT), "Geographic profiles output missing."
    with open(config.GEO_PROFILES_OUTPUT, "r") as f:
        data = json.load(f)

    # Validate output schema
    assert "metadata" in data
    assert "counties" in data
    
    # Metadata assertions
    meta = data["metadata"]
    assert "total_counties" in meta
    assert "counties_with_2plus_sources" in meta
    assert isinstance(meta["data_sources_joined"], list)
    
    # CMS Medicaid Proxy assertion 
    assert any("Medicaid Supply Proxy" in s for s in meta["data_sources_joined"])

    # County records validation
    assert len(data["counties"]) > 0
    record = data["counties"][0]
    assert "fips_code" in record
    assert "state_abbr" in record
    assert "county" in record
    assert "population" in record
